version: "3"

services:
  pg:
    image: postgres:16
    restart: always
    ports: 
      - ${DB_PORT}:${PG_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
         
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
        - ./backup:/backups
    links:
        - pg
    depends_on:
        - pg
    environment:
        - POSTGRES_HOST=pg
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
     #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
        - POSTGRES_EXTRA_OPTS=-Z9 --blobs --clean
        - SCHEDULE=@daily
        # - SCHEDULE=@every 1m
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8181
